version: '3.4'

services:
  alltheminutesupdated:
    container_name: all-the-minutes-v2
    build:
      context: .
      dockerfile: ./Dockerfile
    image: f4zphp27xi2s27yn/my_repo_topor:alltheminutesupdated
    environment:
      - NODE_ENV
      - TWITTER_API_KEY
      - TWITTER_API_KEY_SECRET
      - ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET
      - TWITTER_USER_ID
    volumes:
      - ${CONTAINER_DATA_LOCATION}:/usr/src/app/db:rw
